sonarqube

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,31 +14,40 @@ jobs:
 
     steps:
       - uses: actions/checkout@v6.0.2
+        with:
+          # Disabling shallow clones is recommended for improving the relevancy of reporting
+          fetch-depth: 0
 
-      - name: Install dependencies
-        run: npm install
+      # - name: Install dependencies
+      #   run: npm install
 
-      - name: Test
-        uses: mattallty/jest-github-action@v1.0.3
+      # - name: Test
+      #   uses: mattallty/jest-github-action@v1.0.3
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   with:
+      #     test-command: "npm run coverage-jenkins"
+
+      # - uses: actions/upload-artifact@v4
+      #   if: success() || failure()
+      #   with:
+      #     name: test-results
+      #     path: |
+      #       ./coverage/test.results.xml
+      #       ./coverage/
+
+      # - name: Save Code Linting Report JSON
+      #   run: npm run lint:json
+      #   continue-on-error: true 
+
+      # - name: Annotate Code Linting Results
+      #   uses: ataylorme/eslint-annotate-action@3.0.0
+      #   with:
+      #     repo-token: "${{ secrets.GITHUB_TOKEN }}" 
+      #     report-json: "./coverage/eslint-result.json"
+
+      - name: SonarQube Scan
+        uses: SonarSource/sonarqube-scan-action@v7.1.0
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          test-command: "npm run coverage-jenkins"
-
-      - uses: actions/upload-artifact@v4
-        if: success() || failure()
-        with:
-          name: test-results
-          path: |
-            ./coverage/test.results.xml
-            ./coverage/
-
-      - name: Save Code Linting Report JSON
-        run: npm run lint:json
-        continue-on-error: true 
-
-      - name: Annotate Code Linting Results
-        uses: ataylorme/eslint-annotate-action@3.0.0
-        with:
-          repo-token: "${{ secrets.GITHUB_TOKEN }}" 
-          report-json: "./coverage/eslint-result.json" 
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: https://sonarqube.cnsa-2026-dsa069.tech
